### ISSUE TITLE
Entry validation not being triggered on creation by editor.

### ISSUE THREAD

**Issue by JamesMcFall** [verbb/workflow#18]
Hey guys.
Entries created by editors on my site are created as draft/not-enabled entries. Meaning no validation rules are triggered at all.

These draft entries are able to be submitted to the publishers for review.

This is a problem obviously as the publishers are now having to do a tonne of extra work going through and re-checking all of the required fields are filled in.

I could be wrong but I don't think this was always the case. Our QA review on the site brought up the need to be able to save incomplete entries because they couldn't. But I can't think of anything that could have changed.

Any suggestions? 

Thanks :)

**Comment by engram-design** [comment]
Thats interesting to hear - can you save an entry as a draft or disabled entry without the validation rules being triggered? I didn't even realise this was the case, and surprised Craft lets you do that.

Slightly related to [#6](https://github.com/engram-design/Workflow/issues/6), so it looks like I might have to end up writing some sort of saving mechanism. Either that, or we run the entry to be submitted through its validation rules. I wonder if there is a case for submitting an un-finished entry for review in some cases?

**Comment by JamesMcFall** [comment]
Hey Josh.
Yeah you totally can save empty entries (draft & disabled) - even without a title. It just sets it as "New Entry", at least within Craft 2.6.

If the validation rules could be triggered on submission (and a save, like issue #6) that'd be amazing. I imagine that might be a little tricky if you're leveraging the existing entry statuses though and craft is doing this huh?

**Comment by JamesMcFall** [comment]
Oh wow yeah we’ve had a site go live with Workflow and have had 20-30 editors jump in and almost all of the entries aren’t filled in correctly as they’re not being validated (users ignoring the asterisks on the fields). There’s another expected 100 editors signing up in the next couple of days.

That's a real problem :/ I'm going to try to hack a solution together and if it works alright I'll let you know what I did :)

**Comment by engram-design** [comment]
Happy to look into this tonight if you need it sorted. Feel free to hit me up on Slack.

**Comment by JamesMcFall** [comment]
Thanks again for offering to look into that last night. 

I didn't have any luck with my solution (turns out trying to validate an entry when it has lots of custom fields is infeasibly difficult in Craft 2). I did track down [this plugin](https://github.com/mmikkel/AlwaysValidate-Craft) that forces disabled and draft entries to be validated - which mitigates the issue I was having

I'll leave it up to you as to whether to close the issue or not :)

https://github.com/mmikkel/AlwaysValidate-Craft

**Comment by engram-design** [comment]
Ah, thats a nice little plugin! Leaving open for now, just to decide how to tackle this one :)

**Comment by engram-design** [comment]
This should be improved in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0), where submission for approval triggers the regular entry-save events.
