### ISSUE TITLE
Workflow entry title should link to draft version

### ISSUE THREAD

**Issue by yohoGDES** [verbb/workflow#19]
When an editor submits a draft for review as a workflow, the link on the workflow list and email the content publisher receives should link to the version of the entry that was submitted instead of the current version of the entry. 

Example: currently it links to '/admin/entries/homepage'
It would be nice to link to: '/admin/entries/homepage/drafts/4'

**Comment by engram-design** [comment]
This has been fixed in [1.0.0](https://github.com/verbb/workflow/releases/tag/1.0.0) for Craft 3.
