### ISSUE TITLE
Draft / Version Diff Tool?

### ISSUE THREAD

**Issue by yohoGDES** [verbb/workflow#20]
This very well may be out of the scope of Workflow, but it would be an incredibly helpful feature for approving workflows. It would be nice to have a UI to compare diffs between versions or drafts, that way publishers could clearly see what has changed in the content. 

This is a request in core, but could fit Workflow: https://craftcms.uservoice.com/forums/285221-feature-requests/suggestions/9936945-compare-drafts-diff-tool-for-entries

Also referenced here: http://craftcms.stackexchange.com/questions/13277/comparing-2-versions-of-an-entry-and-highlighting-the-changes

**Comment by SimonEast** [comment]
Yes, I agree this would be useful, but in practice it can get incredibly complicated, especially when using Matrix fields (or heck, what about nested Neo fields?). A diff algorithm would have to take all of these into account and render them in an intelligent way to the user, so it's not a small feat.

**Comment by Coysh** [comment]
Jumping on an old issue - but it's still open. I think this would be great to have.

**Comment by engram-design** [comment]
Added in [2.0.0](https://github.com/verbb/workflow/releases/tag/2.0.0). Refer to [blog post](https://verbb.io/blog/workflow-2) and [upgrade docs](https://verbb.io/craft-plugins/workflow/docs/get-started/upgrading-from-v1).
