### ISSUE TITLE
Its Dangerous to install the Plugin without a Usergroup

### ISSUE THREAD

**Issue by gisu** [verbb/workflow#22]
I want to test the Plugin, without any Usergroup, and now i getting CException Errors on the Backend.

![image](https://cloud.githubusercontent.com/assets/442468/22936477/f065608e-f2d5-11e6-8040-216ad7017c71.png)

**Comment by engram-design** [comment]
This has been fixed in [1.0.0](https://github.com/verbb/workflow/releases/tag/1.0.0) for Craft 3.
