### ISSUE TITLE
Craft update to 2.6.2987

### ISSUE THREAD

**Issue by mng123** [verbb/workflow#23]
Hi, After the Craft update to 2.6.2987, the entries are giving the error "in_array() expects parameter 2 to be array, string given"

The only way to access the entries for editing is by disabling the workflow plugin.

Are there any suggestion on resolving this?

**Comment by engram-design** [comment]
This has been fixed in [1.0.0](https://github.com/verbb/workflow/releases/tag/1.0.0) for Craft 3.
