### ISSUE TITLE
Publisher updating content for immediate publishing

### ISSUE THREAD

**Issue by simongoh** [verbb/workflow#24]
Sometimes, publishers need to have the flexibility to just make some edits and publish the content, without the need to route the content back to the editor.

Can this be done? We are having some productivity issues because the publisher cannot make edits and publish because the Save button is missing.

**Comment by engram-design** [comment]
This has been fixed in [1.0.0](https://github.com/verbb/workflow/releases/tag/1.0.0) for Craft 3.
