### ISSUE TITLE
Rework submission button to save entry content and submit

### ISSUE THREAD

**Issue by engram-design** [verbb/workflow#6]
Currently requires you to save the entry first, then submit.

**Comment by outline4** [comment]
+1!

**Comment by engram-design** [comment]
This won't be getting implemented any time soon, as it requires too much native entry-saving implementation that I'm comfortable with. While it'd be great to simply call the native `entries/saveEntry` controller action, it'll redirect before Workflow has time to run its logic. I would rather not double-up on the code in this action.

Additionally, once a entry has been published, an editor can no longer save an entry - instead it must be saved as a new draft. Another case to be aware of

These and a few other complexities are why I'd rather not implement this for the time being. Obviously it _can_ be done, but I'm wary or running too much default entry saving logic into this plugin (more things to break!).

**Comment by paul-blundell** [comment]
+1

I have not tested this but could you not use some javascript so when you click the Submit for Review button it adds a hidden input field, changes the forms action url to `entryRevisions/saveDraft` to force a new Draft, submits the form and then use the hook `entryRevisions.onSaveDraft` to check the request post params for the input field you added to the form and if present redirect to `submissions/sendForSubmission` with the entry id and draft id.

**Comment by engram-design** [comment]
Well, this was tricky to pull off in Craft 2, but fortunately in Craft 3, its actually much more feasibly possible. Added in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0)
